{% set name = "pymssql" %}
{% set version = "2.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e86c28fa71a66da3a89584b16b69dec09fed97feadb7eaf487c70493653fc63
  patches:
    - patches/0001-customize-compiler.patch

build:
  number: 0
  script:
    - export LINK_FREETDS_STATICALLY=NO   # [unix]
    - set LINK_FREETDS_STATICALLY=NO      # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    #- {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - packaging >=24.2
    - setuptools >80.0
    - setuptools-scm >=8.0
    - wheel >=0.36.2
    - cython >=3.1.0
    - tomli
    - freetds
  run:
    - python
    - freetds

test:
  source_files:
    - tests
  imports:
    - pymssql
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - psutil

about:
    dev_url: https://github.com/pymssql/pymssql
    doc_url: https://www.pymssql.org
    home: https://pymssql.org
    license: LGPL-2.1-only
    license_family: LGPL
    license_file: LICENSE
    summary: DB-API interface to Microsoft SQL Server for Python. (new Cython-based
        version)
    description: |
      A simple database interface for Python that builds on top of FreeTDS to provide a Python DB-API (PEP-249) interface to Microsoft SQL Server.
      The wheels of pymssql are built against the latest release of FreeTDS and could be found on PyPI Project.

extra:
  recipe-maintainers:
    - mariusvniekerk
