{% set name = "pymssql" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18089641b687be1ebd0f64f0d1ff977478a397ffa1af372bdf10dbec29cf6d2e

build:
  number: 0
  skip: True  # [py<37]
  script:
    - export LINK_FREETDS_STATICALLY=NO   # [unix]
    - set LINK_FREETDS_STATICALLY=NO      # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython >=3.0.10
  host:
    - python
    - cython >=3.0.10
    - freetds
    - pip
    - setuptools >=54.0
    - setuptools-git
    - setuptools_scm >=5.0
    - toml
    - wheel >=0.36.2
  run:
    - python
    - freetds

test:
  imports:
    - pymssql
  requires:
    - pip
  commands:
    - pip check

about:
    dev_url: https://github.com/pymssql/pymssql
    doc_url: https://www.pymssql.org/en/stable/
    home: https://pymssql.org
    license: LGPL-2.1-only
    license_family: LGPL
    summary: DB-API interface to Microsoft SQL Server for Python. (new Cython-based
        version)

extra:
  recipe-maintainers:
    - mariusvniekerk
