travis:
  secure:
    BINSTAR_TOKEN: ATp55BgDShuJ6NnMvUtZ1+ifRDTnvXChhvi7GuGQHMxiK1+8t6m+PQAbAlnNV2ctrKTasvMZDYYTetX0C8pnzOXZkmxosyI3R0NXBibYm+bKGUSv4e0bOL/kxl61kKXRetbiivSctaaXC+ADsWC5Z+2uocUbnd74PU1NRHkIxBEonZgFl3DlFknLDpwa61yjSVayFwG8+fGesuERI0itWV0r05g4xR+Ag1+SZPrcEagUnqq/59W9+dOw2nB4cyth7xVDMdqpr+N6v/kC9zC2KaYU3hzgwpMBGetzmauD7WZdIDoD/5zfB+tA/SdieNLohIyT16yQ3RQgzTKDGpeTHpaH9FjOyC80mBvXkVfumCPiFxqW/l5LBAxzjcjRnsNO02EnA3nA3fxIB5OY/PqchjV52ewaBNZn4y0yF4Ephc8FdX/KKxEDmfXrlGKp8M9qKdAPnjEO9mtow4Y0cnNnV4uM1KrGg0EEQpeS9V3F2a0VAFOoUGykScg1inHgM0Z+E4Fx82uh5fqPMVK2C08Uw7661InEHmhJt30urt3vsTGvfUjuCsmP6Df1mEaPGltnzvS+EnF+DRNLYxbG/yabnQsj9DZgP+iRC4ylY6yyb9VPffjmIHiV/nJMcs7sfZMOe7YDlIKN8eTQ96XGOwtVm8I2rSIi8lc3teYXkyBV5k4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
